import Head from "next/head";
import Image from "next/image";
import { Montserrat } from "@next/font/google";
import styles from "../styles/Home.module.scss";
import Input from "../components/Input/Input";
import Button from "../components/Button/Button";
import { useState } from "react";
import { useRouter } from "next/router";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"]
});

export default function Home() {
  const [username, setUsername] = useState("");
  const [error, setError] = useState("");
  const router = useRouter();

  const onUsernameChange = (value: string) => {
    setUsername(value);
    setError("");
  };

  const checkUsername = async () => {
    if (!username) {
      setError("Please insert a username");
      return;
    }

    const response = await fetch("/api/users/create", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ username })
    });
    const data = await response.json();
    if (data.status === 400) {
      return setError(data.message);
    }

    localStorage.setItem("username", username);
    router.push("/chat");
  };

  return (
    <>
      <Head>
        <title>Websocket test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div>
          <div>
            <h1>Insert a username</h1>
          </div>
          <div className={styles.form}>
            <Input
              setValue={onUsernameChange}
              value={username}
              placeholder="Username"
              error={error}
            />
            <Button onClick={checkUsername} label="Let's chat" />
          </div>
        </div>
      </main>
    </>
  );
}
